export const attributes = {
  athletes: [
    'Chris Mazdzer',
    'Gus Kenworthy',
    'Hilary Knight',
    'Joey Mantia',
    'John Shuster',
    'Kendall Coyne Schofield',
    'Lindsey Jacobellis',
    'Nancy Kerrigan',
    'Red Gerard',
    'Tina Maze',
  ],
  backgrounds: ['Crystals', 'Frost', 'Lights', 'Wind'],
  signed: ['Yes', 'No'],
  sports: [
    'Alpine Skiing',
    'Curling',
    'Figure Skating',
    'Freestyle Skiing',
    'Ice Hockey',
    'Luge',
    'Snowboard',
    'Speed Skating',
  ],
  tiers: ['Common', 'Bronze', 'Silver', 'Gold'],
};
